---
- name: K8S | pull calico from goodrain.me
  shell: "docker pull goodrain.me/{{ calico_image }}"
  ignore_errors: true

#- name: Network | Copy Calico Service
#  template:
#    src: calico.service.j2
#    dest: /etc/systemd/system/calico.service

- name: Rainbond | Copy Network Role
  template:
    src: network.role.j2
    dest: "{{ node_role_dir }}/network.yaml"

- name: Network | Copy calico conf
  template:
    src: calico.conf.j2
    dest: /opt/rainbond/etc/cni/10-calico.conf

- name: Network | Copy calicoctl binary from deploy
  copy:
    src: "{{ local_tools }}/bin/calicoctl"
    dest: "{{ bin_dir }}/calicoctl"
    mode: 0755

#- name: Network | start calico
#  shell: "systemctl daemon-reload && systemctl enable calico && systemctl start calico"