---
- name: Rainbond | Prepare Up Node
  template:
    src: nodeup.sh.j2
    dest: /tmp/nodeup.sh
    mode: 0777

- name: Rainbond | Up Node 
  shell: "bash /tmp/nodeup.sh"
  register: nodeup_task_result
  until: nodeup_task_result is succeeded
  retries: 5