---
- name: Health | Add Health Role
  template:
    src: health.role.j2
    dest: "{{ node_role_dir }}/health.yaml"

- name: Rainbond | Add Dns Role
  template:
    src: dns.role.j2
    dest: "{{ node_role_dir }}/dns.yaml"

- name: Health | Add Dns Health Check
  template:
    src: "{{ base_dir }}/hack/files/health/rbd-dns.sh"
    dest: "{{ rbd_dir }}/health/rbd-dns.sh"
    mode: 0777

- name: Health | Add local Dns Health Check
  template:
    src: local-dns.sh.j2
    dest: "{{ rbd_dir }}/health/local-dns.sh"
    mode: 0777

- name: Health | Add network Health Check
  template:
    src: "network_{{ CLUSTER_NETWORK }}.sh.j2"
    dest: "{{ rbd_dir }}/health/network.sh"
    mode: 0777
  tags: health

- name: Health | Add Storage Health Check
  template:
    src: "{{ base_dir }}/hack/files/health/storage.sh"
    dest: "{{ rbd_dir }}/health/storage.sh"
    mode: 0777

- name: Rainbond | check cni bin
  stat: path="{{ rbd_dir }}/bin/calico"
  register: re_cni_is_done

- name: Rainbond | Copy cni bin
  copy: src={{ item }} dest={{ rbd_dir }}/bin owner=root mode=777
  with_fileglob:
    - "{{ rbd_dir }}/etc/tools/cni/bin/*"
  when: re_cni_is_done.stat.isreg is not defined

- name: Rainbond | Copy tools
  copy: src={{ item }} dest={{ bin_dir }} owner=root mode=777
  with_fileglob:
    - "{{ rbd_dir }}/etc/tools/bin/*"
  when: re_cni_is_done.stat.isreg is not defined

- name: Rainbond | check kubecfg
  stat: path="{{ kubecfg_dir }}/token.csv"
  register: ck_kubecfg_is_done

- name: Rainbond | Copy kubecfg
  copy: src={{ item }} dest={{ kubecfg_dir }}
  with_fileglob:
    - "{{ kubecfg_dir }}/*"
  when: ck_kubecfg_is_done.stat.isreg is not defined

- name: Rainbond | check ssl
  stat: path="{{ ca_dir }}/ca.pem"
  register: ck_ssl_is_done

- name: Rainbond | Copy ssl
  copy: src={{ item }} dest={{ ca_dir }}
  with_fileglob:
    - "{{ ca_dir }}/*"
  when: ck_ssl_is_done.stat.isreg is not defined

- name: Rainbond | check region ssl
  stat: path="{{ region_ca_dir }}/ca.pem"
  register: ck_ca_ssl_is_done

- name: Rainbond | Copy region ssl
  copy: src={{ item }} dest={{ region_ca_dir }}
  with_fileglob:
    - "{{ region_ca_dir }}/*"
  when: ck_ca_ssl_is_done.stat.isreg is not defined

#- name: Rainbond | Check docker.env
#  stat: path=/opt/rainbond/envs/docker.sh
#  register: docker_install_by_rainbond

- name: Health | Copy docker check
  template:
    src: "{{ base_dir }}/hack/files/health/check_docker.sh"
    dest: "{{ rbd_dir }}/health/check_docker.sh"
    mode: 0777

- name: Health | Add Health Only Health Role
  template:
    src: only_health.role.j2
    dest: "{{ node_role_dir }}/only_health.yaml"
#  when: docker_install_by_rainbond.stat.isreg is defined
