---
- name: Health | Add Health Role
  template:
    src: health.role.j2
    dest: "{{ node_role_dir }}/health.yaml"

- name: Rainbond | Add Dns Role
  template:
    src: dns.role.j2
    dest: "{{ node_role_dir }}/dns.yaml"

- name: Health | Add Dns Health Check
  template:
    src: "{{ base_dir }}/hack/files/health/rbd-dns.sh"
    dest: "{{ rbd_dir }}/health/rbd-dns.sh"
    mode: 0777

- name: Health | Add local Dns Health Check
  template:
    src: local-dns.sh.j2
    dest: "{{ rbd_dir }}/health/local-dns.sh"
    mode: 0777

- name: Health | Add network Health Check
  template:
    src: "network_{{ CLUSTER_NETWORK }}.j2"
    dest: "{{ rbd_dir }}/health/network.sh"
    mode: 0777

- name: Health | Add Dns Health Check
  template:
    src: "{{ base_dir }}/hack/files/health/storage.sh"
    dest: "{{ rbd_dir }}/health/storage.sh"
    mode: 0777