---
- name: Rainbond | Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Rainbond | Include overrides specific to RHEL 7.
  include_vars: RedHat-7.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == "7"

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure directories to export exist
  file: 'path="/grdata" state=directory'


- name: Ensure nfs is running.
  service: "name={{ nfs_server_daemon }} state=started enabled=yes"

- name: Copy exports file.
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: reload nfs

- name: Update exports
  shell: "exportfs -ra"


- name: Health | Copy health storage check
  template:
    src: check.sh.j2
    dest: /tmp/check_storage.sh
    owner: root
    group: root
    mode: 0777

- name: Health | Run health storage check
  shell: "bash /tmp/check_storage.sh"
