# [optional] to synchronize time of nodes with 'chrony' 
#- hosts: all
#  roles:
#  - { role: chrony, when: "hostvars[groups.deploy[0]]['NTP_ENABLED'] == 'yes'" }

# to create CA, kubeconfig, kube-proxy.kubeconfig etc. on 'deploy' node
#- hosts: deploy
#  roles:
#  - deploy

# prepare tasks for all nodes
- hosts: all
  roles:
    - { role: rainvar, tags: default }
    - { role: prepare, tags: prepare }

