- hosts: lb
  roles:
    - { role: rainvar, tags: default }
    - { role: bootstrap, tags: bootstrap }
    - { role: prepare, tags: prepare }
    - { role: docker/install, tags: docker }
    - { role: network_plugin/calico, when: "CLUSTER_NETWORK == 'calico'" }
    - { role: network_plugin/flannel, when: "CLUSTER_NETWORK == 'flannel'" }
    - { role: lb, tags: lb }
    - { role: node/exlb, tags: exnode }