---
nodeip: "{{hostvars[inventory_hostname]['ip']}}"
nodeid: "{{ inventory_hostname }}"
run_mode: |-
  {%- if inventory_hostname in groups['manage'] + groups['new-manage'] -%}master{%- else -%}worker{%- endif -%}
