---
nodeip: "{{hostvars[inventory_hostname]['ip']}}"
run_mode: |-
  {%- if inventory_hostname in groups['master'] + groups['new-master'] -%}master{%- else -%}worker{%- endif -%}
noderule: |-
  {%- if inventory_hostname in groups['master'] + groups['new-master'] -%}
    {%- if deploy_type == "thirdparty" -%}
      manage,gateway
    {%- else -%}
      {%- if inventory_hostname in groups['worker'] -%}
        manage,compute,gateway
      {%- else -%}
        manage,gateway
      {%- endif -%}
    {%- endif -%}
  {%- elif inventory_hostname in groups['new-worker'] + groups['lb'] -%}
      compute,gateway
  {%- else -%}
      compute
  {%- endif -%}

