---
- name: Check | Check if base.image.tgz is download
  stat: path="{{ local_offline }}/base.images.tgz"
  register: check_image_base_tgz_download

- name: The next task may take some time to execute
  debug:
    msg: "The next task may take some time to execute: Waiting downloading base.images.tgz (1.5GB)"
  when: check_image_base_tgz_download.stat.isreg is not defined

- name: Rainbond | Download base image tgz ok
  get_url:
    url: "{{ base_images_url }}"
    dest: "{{ local_offline }}/base.images.tgz"
#    checksum: "{{ base_images_sha256 }}"
  when: check_image_base_tgz_download.stat.isreg is not defined

- name: Check | Check if rainbond.image.tgz is download
  stat: path="{{ local_offline }}/rainbond.images.tgz"
  register: check_image_rainbond_tgz_download

- name: The next task may take some time to execute
  debug:
    msg: "The next task may take some time to execute: Waiting downloading rainbond.images.tgz (300MB)"
  when: check_image_rainbond_tgz_download.stat.isreg is not defined

- name: Rainbond | Download rainbond image tgz ok
  get_url:
    url: "{{ rainbond_images_url }}"
    dest: "{{ local_offline }}/rainbond.images.tgz"
#    checksum: "{{ rainbond_images_sha256 }}"
  when: check_image_rainbond_tgz_download.stat.isreg is not defined
