---
- name: Check presence of fastestmirror.conf
  stat:
    path: /etc/yum/pluginconf.d/fastestmirror.conf
  register: fastestmirror

# fastestmirror plugin actually slows down Ansible deployments
- name: Disable fastestmirror plugin
  lineinfile:
    dest: /etc/yum/pluginconf.d/fastestmirror.conf
    regexp: "^enabled=.*"
    line: "enabled=0"
    state: present
  become: true
  when: fastestmirror.stat.exists

- name: Add proxy to /etc/yum.conf if http_proxy is defined
  lineinfile:
    path: "/etc/yum.conf"
    line: "proxy={{ http_proxy }}"
    create: yes
    state: present
  become: true
  when: http_proxy is defined

- name: PKG| remove centos pkg
  yum: 
    name: 
      - firewalld
      - python-firewall
      - firewalld-filesystem
#      - container-selinux
      - dnsmasq
      - nscd
    state: absent
  tags: prepare

- name: PKG| add EPEL repo
  yum: name=epel-release state=latest
  when: install_type == "online"

- name: PKG| install centos package
  yum: 
    name: 
      - conntrack-tools     # ipvs mode
      - psmisc       
      - nfs-utils     
      - jq                  
      - socat               # port forwarding
      - bash-completion     
      - rsync               
      - ipset
      - ipvsadm
      - net-tools
      - expect
    state: latest

- name: SYSTEM | disable selinux
  shell: "setenforce 0"
  failed_when: false

- name: SYSTEM | disable selinux forover
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"
