---
- import_tasks: offline.yml
  when: install_type == "offline"

- import_tasks: check.yml

- import_tasks: debian.yml
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- import_tasks: centos.yml
  when: ansible_distribution == "CentOS"

- import_tasks: setup-pipelining.yml

# General configuration
- import_tasks: common.yml 