---
- name: Offline | Creates init directory
  file: path=/opt/rainbond/.init state=directory

- name: Offline | Creates backup directory
  file: path=/etc/yum.repos.d/backup state=directory

- name: Offline | Check offline repo
  stat: path=/opt/rainbond/.init/.offline
  register: offline_repo

- name: Offline | Clean old Repository
  shell: mv -f /etc/yum.repos.d/*.repo /etc/yum.repos.d/backup && touch /opt/rainbond/.init/.offline
  when: ansible_distribution == "CentOS" and offline_repo.stat.isreg is not defined

- name:  Offline | Add CentOS Repository
  template: src=rainbond.repo.j2 dest=/etc/yum.repos.d/rainbond.repo
  when: ansible_distribution == "CentOS" and offline_repo.stat.isreg is not defined

- name: Offline | yum-clean-metadata
  command: yum clean all
  args:
    warn: no
  when: ansible_distribution == "CentOS"