---
- name: Copy Docker Offline Install Script
  template:
    src: get_docker.sh.j2
    dest: /tmp/install_docker.sh
    mode: 0777

- name: Install docker offline
  shell: "bash /tmp/install_docker.sh"
  register: docker_task_result
  until: docker_task_result is succeeded
  retries: 4

- name: Start docker if succeeded
  service:
    name: docker
    enabled: yes
    state: started