---
nodeip: "{{hostvars[inventory_hostname]['ip']}}"
run_mode: |-
  {% if inventory_hostname in groups['master'] %}master{% else %}worker{% endif %}
noderule: |-
  {% if inventory_hostname in groups['master'] %}
    {% if inventory_hostname in groups['worker'] %}
      manage,compute
    {% else %}
      manage
    {% endif %}
  {% else %}
      compute
  {% endif %}
