---
- name: Etcd | run if image is pulled
  command: /usr/local/bin/check_img etcd

- name: Etcd | check if image is pulled
  stat: path="/tmp/check_etcd_img"
  register: check_etcd_img

- name: Etcd | pull etcd from goodrain.me
  shell: "docker pull goodrain.me/{{ etcd_image }}"
  when: check_etcd_img.stat.isreg is not defined

- name: Etcd | Copy Etcd Role
  template:
    src: etcd.role.j2
    dest: "{{ node_role_dir }}/etcd.yaml"
  when: deploy_type == "onenode"

- name: Thirdparty | Copy Etcd Role
  template:
    src: retcd.role.j2
    dest: "{{ node_role_dir }}/etcd.yaml"
  when: deploy_type == "thirdparty"

- name: Etcd | Copy Etcd Script
  template:
    src: start-etcd.sh.j2
    dest: "{{ script_dir }}/start-etcd.sh"
    mode: 0777
  when: deploy_type == "onenode"

- name: Thirdparty | Copy Etcd Script
  template:
    src: start-retcd.sh.j2
    dest: "{{ script_dir }}/start-retcd.sh"
    mode: 0777
  when: deploy_type == "thirdparty"

- name: Etcd | Copy add cluster
  template:
    src: add-cluster.sh.j2
    dest: "{{ script_dir }}/add-cluster.sh"
    mode: 0777

- name: Etcd | Copy Etcd env
  template:
    src: etcd.sh.j2
    dest: "{{ env_dir }}/etcd.sh"
    mode: 0777

- name: Etcd | Copy Etcd Service
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
  when: deploy_type == "onenode"

- name: Thirdparty | Copy Etcd Service
  template:
    src: retcd.service.j2
    dest: /etc/systemd/system/retcd.service
  when: deploy_type == "thirdparty"

- name: Etcd | Copy etcdctl binary from deploy
  copy: 
    src: "{{ local_tools }}/bin/etcdctl"
    dest: "{{ bin_dir }}/etcdctl"
    mode: 0755

- name: Etcd | Run add etcd cluster
  shell: "bash {{ script_dir }}/add-cluster.sh > /tmp/etcd.cluster.log"
  register: add_etcd_cluster_task_result
  until: add_etcd_cluster_task_result is succeeded
  retries: 3

- name: Etcd | start etcd
  shell: "systemctl daemon-reload && systemctl enable etcd && systemctl start etcd"
  when: deploy_type == "onenode"

- name: Thirdparty | start etcd
  shell: "systemctl daemon-reload && systemctl enable retcd && systemctl start retcd"
  when: deploy_type == "thirdparty" 
