---
- name: Etcd | run if image is pulled
  command: /usr/local/bin/check_img etcd

- name: Etcd | check if image is pulled
  stat: path="/tmp/check_etcd_img"
  register: check_etcd_img

- name: Etcd | pull etcd from goodrain.me
  shell: "docker pull goodrain.me/{{ etcd_image }}"
  when: check_etcd_img.stat.isreg is not defined

- name: Etcd | Copy Etcd Role
  template:
    src: etcd.role.j2
    dest: "{{ node_role_dir }}/etcd.yaml"

- name: Etcd | Copy Etcd Script
  template:
    src: start-etcd.sh.j2
    dest: "{{ script_dir }}/start-etcd.sh"
    mode: 0777

- name: Etcd | Copy Etcd Service
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service

- name: Etcd | Copy etcdctl binary from deploy
  copy:
    src: "{{ local_tools }}/bin/etcdctl"
    dest: "{{ bin_dir }}/etcdctl"
    mode: 0755

- name: Etcd | start etcd
  shell: "systemctl daemon-reload && systemctl start etcd"

