---
- name: check nfs server
  shell: "ls /grdata/kubernetes/kube-proxy.kubeconfig"
  register: check_server
  ignore_errors: true

- name: debug
  debug: var=check_server

- name: install nfs client debian
  action: apt pkg=nfs-common state=present
  when: is_debian_or_ubuntu and check_server.rc != 0
  tags:
    - nfs

- name: install nfs client centos
  action: yum pkg=nfs-utils state=present
  when: is_centos and check_server.rc != 0
  tags:
    - nfs

- name: Ensure rpcbind is running (CentOS)
  action: service name=rpcbind state=started enabled=yes
  when: is_centos and check_server.rc != 0

- name: Ensure rpcbind is running (Ubuntu Trusty Tahr or newer)
  action: service name=rpcbind state=started enabled=yes
  when: is_ubuntu|bool and ansible_lsb.major_release is defined and ansible_lsb.major_release|int >= 14 and check_server.rc != 0

- name: Ensure rpcbind is running (Debian)
  action: service name=rpcbind state=started enabled=yes
  when: is_debian and check_server.rc != 0

- name: Ensure {{nfsmount}} directory exists
  action: file path={{nfsmount}} state=directory
  tags: 
    - nfs

- shell: if [ -z "$nfsoptions" ]; then  echo rw,sync,nfsvers=3; else echo $nfsoptions; fi
  register: _nfsopts
  sudo: false
  connection: local
  tags:
    - nfs

- name: configure /etc/fstab on clients
  action: mount name={{nfsmount}} src={{nfsserver}}:{{nfspath}} fstype=nfs opts={{_nfsopts.stdout}} state=mounted
  when: check_server.rc != 0
  tags:
    - nfs