---
# CPU
r6d_min_cpu: 2

# Mem
#r6d_min_ram: 4096
r6d_min_ram: 3500

# Disk
r6d_min_disk: 40000000000

# 设置时间源服务器
ntp_server: "ntp1.aliyun.com"

# 设置允许内部时间同步的网络段，比如"10.0.0.0/8"，默认全部允许
local_network: "0.0.0.0/0"

# 节点ip
nodeip: "{{hostvars[inventory_hostname]['ip']}}"

# 节点模式
run_mode: |-
  {%- if inventory_hostname in groups['master'] -%}master{%- else -%}worker{%- endif -%}

# 节点属性
noderule: |-
  {%- if inventory_hostname in groups['master'] -%}
    {%- if inventory_hostname in groups['worker'] -%}
      manage,compute
    {%- else -%}
      manage
    {%- endif -%}
  {%- else -%}
      compute
  {%- endif -%}