---
- name: Upgrade | Copy Image Upgrade Script
  template:
    src: image.sh.j2
    dest: /tmp/upgradeimage.sh
    mode: 0777

- name: Upgrade | Copy Upgrade db sql
  template:
    src: 5.0.1.sql.j2
    dest: /tmp/5.0.1.sql
    mode: 0777

- name: Upgrade | Upgrade images to goodrain.me
  shell: "bash -x /tmp/upgradeimage.sh > /tmp/5.0.1.upgrade.log"
  register: upgrade501_task_result
  until: upgrade501_task_result is succeeded
  retries: 5

- name: Upgrade | Copy grctl binary from deploy
  copy: 
    src: "{{ local_tools }}/bin/grctl"
    dest: "{{ bin_dir }}/grctl"
    mode: 0755

- name: Upgrade | stop node service
  systemd:
    state: stopped
    name: node

- name: Upgrade | Copy node binary from deploy
  copy: 
    src: "{{ local_tools }}/bin/node"
    dest: "{{ bin_dir }}/node"
    mode: 0755

- name: Tools | Copy Rainbond Tools
  copy: src={{ item }} dest={{ bin_dir }} owner=root mode=777
  with_fileglob:
    - "{{ base_dir }}/hack/files/bin/grtools/*"

- name: Upgrade | start node service
  systemd:
    state: started
    name: node