---
- name: Rainbond | Copy node binary from deploy
  copy:
    src: "{{ local_tools }}/bin/node"
    dest: "{{ bin_dir }}/node"
    mode: 0755

- name: Rainbond | Copy node uuid
  copy:
    src: /opt/rainbond/.init/node.uuid
    dest: /tmp/node.uuid

- name: Rainbond | Prepare check node uuid
  template:
    src: node_uuid.sh.j2
    dest: /tmp/node_uuid.sh
    mode: 0777

- name: Rainbond | Write node uuid
  shell: "bash /tmp/node_uuid.sh > /tmp/write_node.log"

- name: Rainbond | Copy Master Node Rainbond Role 
  template:
    src: master.role.j2
    dest: "{{ node_role_dir }}/master.yaml"
  when: inventory_hostname in groups['master'] + groups['new-master']

- name: Rainbond | Copy Master Node UI Role
  template:
    src: ui.role.j2
    dest: "{{ node_role_dir }}/ui.yaml"
  when: inventory_hostname in groups['master'] + groups['new-master']

- name: Rainbond | Copy Master Node Base Role
  template:
    src: base.role.j2
    dest: "{{ node_role_dir }}/base.yaml"
  when: inventory_hostname in groups['master'] + groups['new-master']

#- name: Rainbond | Copy Master Worker Role
#  template:
#    src: worker.role.j2
#    dest: "{{ node_role_dir }}/worker.yaml"
#  when: inventory_hostname in groups['worker']

- name: Rainbond | Copy Node Script
  template:
    src: start-node.sh.j2
    dest: "{{ script_dir }}/start-node.sh"
    mode: 0755

- name: Rainbond | Copy Node Env
  template:
    src: node.sh.j2
    dest: "{{ env_dir }}/node.sh"
    mode: 0755

- name: Rainbond | Copy Node Services
  template:
    src: node.service.j2
    dest: /etc/systemd/system/node.service

- name: Rainbond | Start Node
  shell: "systemctl daemon-reload && systemctl enable node && systemctl start node"

