---
- name: Copy db init script
  template:
    src: db.sh.j2
    dest: /opt/rainbond/.init/updatedb.sh
    mode: 0777

- name: Copy image push script
  template:
    src: pushimage.sh.j2
    dest: /tmp/install/pushimage.sh
    mode: 0777

- name: Copy check insecure registries
  template:
    src: check_registries.sh.j2
    dest: /tmp/install/check_registries.sh
    mode: 0777

- name: Copy init Sql script
  template:
    src: init.sql.j2
    dest: /opt/rainbond/.init/init.sql

- name: Rainbond | Check goodrain.me
  shell: "bash /tmp/install/check_registries.sh"

- name: Rainbond | Check check_ok
  stat: path="/opt/rainbond/.init/goodrain.me.ok"
  register: check_goodrainme_done

- name: The next task may take some time to execute
  debug:
    msg: "The next task may take some time to execute: Waiting Pushing local images to goodrain.me"
  when: check_goodrainme_done.stat.isreg is defined

- name: Rainbond | Push local images to goodrain.me
  shell: "bash /tmp/install/pushimage.sh"
  register: pushimage_task_result
  until: pushimage_task_result is succeeded
  retries: 5
  when: check_goodrainme_done.stat.isreg is defined

- name: Prepare db
  shell: "bash -x /opt/rainbond/.init/updatedb.sh prepare >> /tmp/install/db.prepare.log"
  register: prepare_db_ok
  until: prepare_db_ok is succeeded
  retries: 5

- name: Migrate ui if prepare_db_ok is succeeded
  shell: "bash -x /opt/rainbond/.init/updatedb.sh migrate >> /tmp/install/db.ui.migrate.log"
  register: migrate_ui_ok
  until: migrate_ui_ok is succeeded
  retries: 5
  when:
    - prepare_db_ok is succeeded

- name: Init Data Region if migrate_ui_ok is succeeded
  shell: "bash -x /opt/rainbond/.init/updatedb.sh config >> /tmp/install/db.init.config.log"
  register: region_init_result
  until: region_init_result is succeeded
  retries: 5
  when:
    - prepare_db_ok is succeeded
    - migrate_ui_ok is succeeded

- name: Check init db if succeeded
  shell: "bash -x /opt/rainbond/.init/updatedb.sh check >> /tmp/install/check.db.log"
  register: checkdb_task_result
  until: checkdb_task_result is succeeded
  retries: 3
  when:
    - prepare_db_ok is succeeded
    - migrate_ui_ok is succeeded
    - region_init_result is succeeded