---
- name: Check CNI
  stat: path="{{ rbd_dir }}/bin/calico"
  register: cni_is_done
  ignore_errors: true

- name: K8S | Copy CNI
  copy: src={{ item }} dest={{ rbd_dir }}/bin owner=root mode=777
  with_fileglob:
    - "{{ rbd_dir }}/etc/tools/cni/bin/*"
  when: cni_is_done.stat.isreg is not defined

- name: K8S | Copy tools
  copy: src={{ item }} dest={{ bin_dir }} owner=root mode=777
  with_fileglob:
    - "{{ rbd_dir }}/etc/tools/bin/*"
  when: cni_is_done.stat.isreg is not defined