---
- name: Check certificates 
  shell: "ls {{ ca_dir }}/kubernetes.pem"
  register: certificates_is_done
  ignore_errors: true

- name: Check kubecfg
  shell: "ls {{ kubecfg_dir }}/token.csv"
  register: kubecfg_is_done
  ignore_errors: true

- name: K8S | check_or_create_certificates
  shell: "docker run --rm -v {{ ca_dir }}:/ssl -w /ssl rainbond/{{ cfssl }} kip {{ MASTER_IP }}"
  when: certificates_is_done.rc != 0 and kubecfg_is_done.rc != 0

- name: K8S | check_or_create_kubeconfig
  shell: "docker run --rm -v {{ ca_dir }}:/etc/goodrain/kubernetes/ssl -v {{ kubecfg_dir }}:/k8s rainbond/{{ kubecfg }}"
  when: certificates_is_done.rc != 0 and kubecfg_is_done.rc != 0

