---
- name: Check | Check if base.image.tgz is unarchive
  stat: path="{{ local_offline }}/images/etcd.tgz"
  register: check_base_image_tgz_unarchive

- name: The next task may take some time to execute
  debug:
    msg: "The next task may take some time to execute: Waiting Unzip base image "

- name: Rainbond | Unzip base image Ok
  unarchive:
    src: "{{ local_offline }}/base.images.tgz"
    dest: "{{ local_offline }}/images"
  when: check_base_image_tgz_unarchive.stat.isreg is not defined

- name: Check | Check if rainbond.image.tgz is unarchive
  stat: path="{{ local_offline }}/images/mq.tgz"
  register: check_rainbond_image_tgz_unarchive

- name: The next task may take some time to execute
  debug:
    msg: "The next task may take some time to execute: Waiting Unzip rainbond image"

- name: Rainbond | Unzip rainbond image Ok
  unarchive:
    src: "{{ local_offline }}/rainbond.images.tgz"
    dest: "{{ local_offline }}/images"
  when: check_rainbond_image_tgz_unarchive.stat.isreg is not defined

- name: Check Push image if Pushed
  stat: path=/tmp/install/push.local.image
  register: check_push_image

- name: The next task may take some time to execute
  debug:
    msg: "The next task may take some time to execute:Waiting load image Ok"
  when: check_push_image.stat.isreg is not defined

- name: Rainbond | load image from local ok
  shell: "bash {{ base_dir }}/offline/images/load.sh > /tmp/install/local.image.log"
  register: load_task_result
  until: load_task_result is succeeded
  retries: 4
  when: check_push_image.stat.isreg is not defined
