---
- name: Rainbond | load image from local
  shell: "bash {{ base_dir }}/offline/images/load.sh > /tmp/local.image.log"
  register: load_task_result
  until: load_task_result is succeeded
  retries: 4