---
- name: Check | Check if image.tgz is unarchive
  stat: path=/grdata/services/offline/images/etcd.tgz
  register: check_image_tgz_unarchive

- name: Rainbond | Unzip base image
  unarchive:
    src: /grdata/services/offline/base.images.tgz
    dest: /grdata/services/offline/images
  when: check_image_tgz_unarchive.stat.isreg is not defined

- name: Rainbond | Unzip rainbond image
  unarchive:
    src: /grdata/services/offline/rainbond.images.tgz
    dest: /grdata/services/offline/images
  when: check_image_tgz_unarchive.stat.isreg is not defined

- name: Rainbond | load image from local
  shell: "bash {{ base_dir }}/offline/images/load.sh > /tmp/local.image.log"
  register: load_task_result
  until: load_task_result is succeeded
  retries: 4