#- name: K8S | pull kubernetes from docker hub
#  docker_image:
#    name: "goodrain.me/hyperkube"
#    tag: "{{ kubernetes_version }}"
#    load_path: "{{  local_imgaes }}/hyperkube.{ kubernetes_version }}.tgz"

#- name: K8S | pull etcd from docker hub
#  docker_image:
#    name: "goodrain.me/etcd"
#    tag: "{{ etcd_version }}"
#    load_path: "{{  local_imgaes }}/etcd.{ etcd_version }}.tgz"

#- name: K8S | pull calico from docker hub
#  docker_image:
#    name: "goodrain.me/calico-node"
#    tag: "{{ calico_version }}"
#    load_path: "{{  local_imgaes }}/calico-node.{ calico_version }}.tgz"

#- name: Rainbond | pull rbd-db from docker hub
#  docker_image:
#    repository: "goodrain.me/rbd-db"
#    tag: "{{ r6d_version }}"
#    load_path: "{{  local_imgaes }}/calico-node.{ calico_version }}.tgz"

#- name: Rainbond | pull tcm from docker hub
#  docker_image:
#    name: "goodrain.me/tcm"
#    tag: "latest"
#    load_path: "{{  local_imgaes }}/tcm.tgz"

#- name: Rainbond | pull mesh from docker hub
#  docker_image:
#    name: "goodrain.me/mesh_plugin"
#    tag: "latest"
#    load_path: "{{  local_imgaes }}/mesh_plugin.tgz"


#- name: Rainbond | pull runner from docker hub
#  docker_image:
#    name: "goodrain.me/runner"
#    tag: "latest"
#    load_path: "{{  local_imgaes }}/runner.{{ r6d_version }}.tgz"

#- name: Rainbond | pull builder from docker hub
#  docker_image:
#    name: "goodrain.me/builder"
#    tag: "latest"
#    load_path: "{{  local_imgaes }}/builder.{{ r6d_version }}.tgz"

#- name: Rainbond | pull adapter from docker hub
#  docker_image:
#    name: "goodrain.me/adapter"
#    tag: "latest"
#    load_path: "{{  local_imgaes }}/adapter.{{ r6d_version }}.tgz"

# - name: Rainbond | pull pause-amd64 from docker hub
#   docker_image:
#     name: "goodrain.me/pause-amd64"
#     tag: "3.0"
#     load_path: "{{  local_imgaes }}/pause-amd64.3.0.tgz"

# - name: Rainbond | pull hub from docker hub
#   docker_image:
#     name: "goodrain.me/rbd-registry"
#     tag: "2.6.2"
#     load_path: "{{  local_imgaes }}/rbd-registry.2.6.2.tgz"

# - name: Rainbond | pull repo from docker hub
#   docker_image:
#     name: "goodrain.me/rbd-repo"
#     tag: "{{ r6d_version }}"
#     load_path: "{{  local_imgaes }}/rbd-repo.{{ r6d_version }}.tgz"

# - name: Rainbond | pull api from docker hub
#   docker_image:
#     name: "goodrain.me/rbd-api"
#     tag: "{{ r6d_version }}"
#     load_path: "{{  local_imgaes }}/rbd-api.{{ r6d_version }}.tgz"

# - name: Rainbond | pull worker from docker hub
#   docker_image:
#     name: "goodrain.me/rbd-worker"
#     tag: "{{ r6d_version }}"
#     load_path: "{{  local_imgaes }}/rbd-worker.{{ r6d_version }}.tgz"

# - name: Rainbond | pull eventlog from docker hub
#   docker_image:
#     name: "goodrain.me/rbd-eventlog"
#     tag: "{{ r6d_version }}"
#     load_path: "{{  local_imgaes }}/rbd-eventlog.{{ r6d_version }}.tgz"

# - name: Rainbond | pull gateway from docker hub
#   docker_image:
#     name: "goodrain.me/rbd-gateway"
#     tag: "{{ r6d_version }}"
#     load_path: "{{  local_imgaes }}/rbd-gateway.{{ r6d_version }}.tgz"

# - name: Rainbond | pull chaos from docker hub
#   docker_image:
#     name: "goodrain.me/rbd-chaos"
#     tag: "{{ r6d_version }}"
#     load_path: "{{  local_imgaes }}/rbd-chaos.{{ r6d_version }}.tgz"

# - name: Rainbond | pull mq from docker hub
#   docker_image:
#     name: "goodrain.me/rbd-mq"
#     tag: "{{ r6d_version }}"
#     load_path: "{{  local_imgaes }}/rbd-mq.{{ r6d_version }}.tgz"

#- name: Rainbond | pull webcli from docker hub
#  docker_image:
#    name: "goodrain.me/rbd-webcli"
#    tag: "{{ r6d_version }}"
#    load_path: "{{  local_imgaes }}/rbd-webcli.{ r6d_version }}.tgz"

#- name: Rainbond | pull rbd-app-ui from docker hub
#  docker_image:
#    name: "goodrain.me/rbd-app-ui"
#    tag: "{{ r6d_version }}"
#    load_path: "{{  local_imgaes }}/rbd-app-ui.{{ r6d_version }}.tgz"

#- name: Rainbond | pull k8s-cni from docker hub
#  docker_image:
#    name: "rainbond/cni:k8s_{{ r6d_version }}"
#    load_path: "{{  local_imgaes }}/cni.k8s_{{ r6d_version }}.tgz"

#- name: Rainbond | pull rbd-cni from docker hub
#  docker_image:
#    name: "rainbond/cni:rbd_{{ r6d_version }}"
#    load_path: "{{  local_imgaes }}/cni.rbd_{{ r6d_version }}.tgz"

#- name: Rainbond | pull kubecfg from docker hub
#  docker_image:
#    name: "rainbond/kubecfg"
#    tag: "dev"
#    load_path: "{{  local_imgaes }}/kubecfg.dev.tgz"

#- name: Rainbond | pull cfssl from docker hub
#  docker_image:
#    name: "rainbond/cfssl"
#    tag: "dev"
#    load_path: "{{ local_imgaes }}/cfssl.dev.tgz"

- name: Rainbond | load image from local
  shell: "bash {{ base_dir }}/offline/images/load.sh"
  register: load_task_result
  until: load_task_result is succeeded
  retries: 4