---
- name: Check | Check if base.image.tgz is download
  stat: path=/grdata/services/offline/base.images.tgz
  register: check_image_base_tgz_download

- name: Rainbond | Download base image tgz
  get_url:
    url: {{ base_images_url }}
    dest: /grdata/services/offline/base.images.tgz
  when: check_image_base_tgz_download.stat.isreg is not defined

- name: Check | Check if rainbond.image.tgz is download
  stat: path=/grdata/services/offline/rainbond.images.tgz
  register: check_image_rainbond_tgz_download

- name: Rainbond | Download rainbond image tgz
  get_url:
    url: {{ rainbond_images_url }}
    dest: /grdata/services/offline/rainbond.images.tgz
  when: check_image_rainbond_tgz_download.stat.isreg is not defined

#- name: Rainbond | write download image.tgz done
#  file: path=/opt/rainbond/.init/tgz.download state=touch
#  when: check_image_tgz_download.stat.isreg is not defined