---
- name: Check Unpack 
  stat: path="{{ local_tools }}/bin/etcdctl"
  register: unpack_is_done
  ignore_errors: true

- name: Rainbond | Unpack rbd cni tools
  shell: "docker run --rm -v {{ local_tools }}:/sysdir rainbond/{{ rbd_cni }} tar zxf /pkg.tgz -C /sysdir"
  when: unpack_is_done.stat.isreg is not defined

- name: Rainbond | Unpack k8s cni tools
  shell: "docker run --rm -v {{ local_tools }}:/sysdir goodrain.me/{{ k8s_cni }} tar zxf /pkg.tgz -C /sysdir"
  when: unpack_is_done.stat.isreg is not defined

