---
master_access_address: "{{hostvars[inventory_hostname]['ip']}}"
etcd_endpoints: |-
  {% for item in groups['etcd'] -%}
    http://{{hostvars[item]['ip']}}:2379{% if not loop.last %},{% endif %}
  {%- endfor %}