---
- name: K8S | pull kubernetes from goodrain.me
  shell: "docker pull goodrain.me/{{ kubernetes_image }}"
  ignore_errors: "true"

- name: Rainbond | Copy K8S Master Role
  template:
    src: k8s-master.role.j2
    dest: "{{ node_role_dir }}/k8s-master.yaml"

- name: Rainbond | Copy Kube apiserver Script
  template:
    src: kube-apiserver.sh.j2
    dest: "{{ script_dir }}/kube-apiserver.sh"
    mode: 0777

- name: Rainbond | Copy Kube controller-manager Script
  template:
    src: kube-controller-manager.sh.j2
    dest: "{{ script_dir }}/kube-controller-manager.sh"
    mode: 0777

- name: Rainbond | Copy Kube scheduler Script
  template:
    src: kube-scheduler.sh.j2
    dest: "{{ script_dir }}/kube-scheduler.sh"
    mode: 0777

- name: Rainbond | Copy Kube audit policy 
  template:
    src: audit-policy.yaml.j2
    dest: "{{ kubecfg_dir }}/audit-policy.yaml"

- name: Rainbond | Copy kubectl binary from deploy
  copy:
    src: "{{ local_tools }}/bin/hyperkube"
    dest: "{{ bin_dir }}/kubectl"
    mode: 0755

- name: Rainbond | Copy kubeconfig from deploy
  copy:
    src: "{{  kubecfg_dir }}/admin.kubeconfig"
    dest: "/root/.kube/config"
    mode: 0755

- name: Rainbond | Copy grctl from deploy
  template:
    src: grctl.yaml.j2
    dest: /root/.rbd/grctl.yaml
